#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# gcloud-deploy.sh — Deploy matcha-cloud to Google Cloud (1 server + 3 clients)
#
# Usage:
#   ./scripts/gcloud-deploy.sh           # deploy everything
#   ./scripts/gcloud-deploy.sh destroy   # tear down all resources
#   ./scripts/gcloud-deploy.sh status    # show IPs and service status
#
# Pre-requisites:
#   - gcloud CLI installed and authenticated (gcloud auth login)
#   - Docker installed locally (only for building if using local build strategy)
#   - A GCP project with billing enabled
#
# By default this script:
#   1. Enables required GCP APIs
#   2. Creates firewall rules
#   3. Generates TLS certs locally, uploads them to Secret Manager
#   4. Creates 4 e2-small VMs (1 server + 3 clients)
#   5. Bootstraps Docker on each VM, clones the repo, and runs containers
#   6. Prints a summary with IPs and URLs
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ══════════════════════════════════════════════════════════════════════════════
# CONFIGURABLE VARIABLES — edit these before running
# ══════════════════════════════════════════════════════════════════════════════
PROJECT_ID="${GCP_PROJECT_ID:-}"        # Required: your GCP project ID
REGION="${GCP_REGION:-us-central1}"
ZONE="${GCP_ZONE:-us-central1-a}"
MACHINE_TYPE="${MACHINE_TYPE:-e2-small}"
IMAGE_FAMILY="${IMAGE_FAMILY:-debian-12}"
IMAGE_PROJECT="${IMAGE_PROJECT:-debian-cloud}"
DISK_SIZE="${DISK_SIZE:-20GB}"

# Repo to clone on the VM (change to your fork if needed)
GIT_REPO="${GIT_REPO:-https://github.com/maldos23/remote-conector.git}"
GIT_BRANCH="${GIT_BRANCH:-main}"

# Auth credentials for the matcha dashboard
MATCHA_USER="${MATCHA_USER:-matcha}"
MATCHA_PASSWORD="${MATCHA_PASSWORD:-m4tcha-cloud}"
JWT_SECRET="${JWT_SECRET:-$(openssl rand -hex 32)}"

# VM names
SERVER_VM="matcha-server"
CLIENT_VMS=("matcha-client-1" "matcha-client-2" "matcha-client-3")

# Firewall tag applied to all VMs
NETWORK_TAG="matcha-cloud"

# Ports
PORT_HTTP=8000
PORT_WSS=8443
PORT_CLIENT=8001

# Local cert paths (generated by this script, never committed)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CERT_DIR="$REPO_ROOT/shared/certs"
CERT="$CERT_DIR/server.crt"
KEY="$CERT_DIR/server.key"

# ══════════════════════════════════════════════════════════════════════════════
# HELPERS
# ══════════════════════════════════════════════════════════════════════════════
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

info()    { echo -e "${CYAN}[matcha]${NC} $*"; }
success() { echo -e "${GREEN}[✓]${NC} $*"; }
warn()    { echo -e "${YELLOW}[!]${NC} $*"; }
error()   { echo -e "${RED}[✗]${NC} $*" >&2; exit 1; }

require_cmd() { command -v "$1" &>/dev/null || error "'$1' not found. Please install it."; }
require_var() { [[ -n "${!1:-}" ]] || error "Environment variable $1 is required. Set it or edit this script."; }

wait_for_vm() {
  local vm="$1" max=30 attempt=0
  info "Waiting for $vm to be ready..."
  while ! gcloud compute ssh "$vm" --zone="$ZONE" --project="$PROJECT_ID" \
    --command="echo ok" --quiet 2>/dev/null; do
    ((attempt++))
    [[ $attempt -ge $max ]] && error "Timeout waiting for $vm"
    sleep 10
  done
  success "$vm is SSH-accessible"
}

get_external_ip() {
  gcloud compute instances describe "$1" \
    --zone="$ZONE" --project="$PROJECT_ID" \
    --format="get(networkInterfaces[0].accessConfigs[0].natIP)" 2>/dev/null
}

# ══════════════════════════════════════════════════════════════════════════════
# DEPLOY STEPS
# ══════════════════════════════════════════════════════════════════════════════

check_prerequisites() {
  info "Checking prerequisites..."
  require_cmd gcloud
  require_cmd openssl
  require_var PROJECT_ID
  gcloud config set project "$PROJECT_ID" --quiet
  success "Prerequisites OK (project=$PROJECT_ID)"
}

enable_apis() {
  info "Enabling GCP APIs..."
  gcloud services enable \
    compute.googleapis.com \
    secretmanager.googleapis.com \
    --project="$PROJECT_ID" --quiet
  success "APIs enabled"
}

create_firewall_rules() {
  info "Creating firewall rules..."

  # Dashboard HTTP
  gcloud compute firewall-rules create matcha-allow-http \
    --project="$PROJECT_ID" \
    --allow="tcp:${PORT_HTTP}" \
    --target-tags="$NETWORK_TAG" \
    --description="matcha-cloud HTTP dashboard" \
    --quiet 2>/dev/null || warn "Firewall rule matcha-allow-http already exists"

  # WSS
  gcloud compute firewall-rules create matcha-allow-wss \
    --project="$PROJECT_ID" \
    --allow="tcp:${PORT_WSS}" \
    --target-tags="$NETWORK_TAG" \
    --description="matcha-cloud WebSocket TLS" \
    --quiet 2>/dev/null || warn "Firewall rule matcha-allow-wss already exists"

  # Client status pages
  gcloud compute firewall-rules create matcha-allow-client \
    --project="$PROJECT_ID" \
    --allow="tcp:${PORT_CLIENT}" \
    --target-tags="$NETWORK_TAG" \
    --description="matcha-cloud client status page" \
    --quiet 2>/dev/null || warn "Firewall rule matcha-allow-client already exists"

  success "Firewall rules ready"
}

generate_and_upload_certs() {
  info "Generating TLS certificates..."
  mkdir -p "$CERT_DIR"

  if [[ ! -f "$CERT" || ! -f "$KEY" ]]; then
    openssl req -x509 -newkey rsa:4096 -sha256 -days 730 -nodes \
      -keyout "$KEY" -out "$CERT" \
      -subj "/CN=matcha-cloud/O=matcha-cloud/C=US" \
      -addext "subjectAltName=IP:0.0.0.0" 2>/dev/null
    success "Certificates generated"
  else
    warn "Certs already exist — reusing. Pass --force-certs to regenerate."
  fi

  info "Uploading certificates to GCP Secret Manager..."

  # Delete and recreate to allow update
  for secret_name in matcha-tls-cert matcha-tls-key matcha-jwt-secret; do
    gcloud secrets delete "$secret_name" --project="$PROJECT_ID" --quiet 2>/dev/null || true
  done

  gcloud secrets create matcha-tls-cert --project="$PROJECT_ID" --data-file="$CERT" --quiet
  gcloud secrets create matcha-tls-key  --project="$PROJECT_ID" --data-file="$KEY"  --quiet
  printf '%s' "$JWT_SECRET" | gcloud secrets create matcha-jwt-secret \
    --project="$PROJECT_ID" --data-file="-" --quiet

  success "Secrets uploaded to Secret Manager"
}

# Bootstrap script that runs on each VM after creation
_vm_bootstrap_docker() {
  cat << 'BOOTSTRAP'
#!/bin/bash
set -e
export DEBIAN_FRONTEND=noninteractive

# Install Docker
apt-get update -qq
apt-get install -y -qq ca-certificates curl gnupg lsb-release git openssl
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(lsb_release -cs) stable" \
  > /etc/apt/sources.list.d/docker.list
apt-get update -qq
apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
systemctl enable docker
systemctl start docker

# Install gcloud (for Secret Manager access)
echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" \
  > /etc/apt/sources.list.d/google-cloud-sdk.list
curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg \
  | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
apt-get update -qq
apt-get install -y -qq google-cloud-cli

echo "Bootstrap complete"
BOOTSTRAP
}

create_server_vm() {
  info "Creating server VM: $SERVER_VM..."

  gcloud compute instances create "$SERVER_VM" \
    --project="$PROJECT_ID" \
    --zone="$ZONE" \
    --machine-type="$MACHINE_TYPE" \
    --image-family="$IMAGE_FAMILY" \
    --image-project="$IMAGE_PROJECT" \
    --boot-disk-size="$DISK_SIZE" \
    --tags="$NETWORK_TAG" \
    --scopes="cloud-platform" \
    --quiet 2>/dev/null || warn "VM $SERVER_VM may already exist"

  wait_for_vm "$SERVER_VM"
  local server_ip; server_ip=$(get_external_ip "$SERVER_VM")

  # Run bootstrap
  gcloud compute ssh "$SERVER_VM" --zone="$ZONE" --project="$PROJECT_ID" \
    --command="$(_vm_bootstrap_docker)" --quiet

  # Run server container
  gcloud compute ssh "$SERVER_VM" --zone="$ZONE" --project="$PROJECT_ID" --quiet -- bash <<REMOTE
set -e

# Download secrets from Secret Manager
mkdir -p /run/secrets
gcloud secrets versions access latest --secret=matcha-tls-cert --project=${PROJECT_ID} > /run/secrets/server.crt
gcloud secrets versions access latest --secret=matcha-tls-key  --project=${PROJECT_ID} > /run/secrets/server.key
chmod 600 /run/secrets/server.key
JWT=\$(gcloud secrets versions access latest --secret=matcha-jwt-secret --project=${PROJECT_ID})

# Clone repo
git clone --branch ${GIT_BRANCH} ${GIT_REPO} /opt/matcha-cloud 2>/dev/null || \
  (cd /opt/matcha-cloud && git pull origin ${GIT_BRANCH})
cd /opt/matcha-cloud

# Build server image
docker build -f server/Dockerfile -t matcha-server:latest .

# Stop old container if running
docker rm -f matcha-server 2>/dev/null || true

# Run server
docker run -d \
  --name matcha-server \
  --restart=always \
  -p ${PORT_HTTP}:8000 \
  -p ${PORT_WSS}:8443 \
  -v /run/secrets:/run/secrets:ro \
  -e HTTP_PORT=8000 \
  -e WS_PORT=8443 \
  -e JWT_SECRET="\$JWT" \
  -e MATCHA_USER=${MATCHA_USER} \
  -e MATCHA_PASSWORD=${MATCHA_PASSWORD} \
  -e TLS_CERT_PATH=/run/secrets/server.crt \
  -e TLS_KEY_PATH=/run/secrets/server.key \
  matcha-server:latest

echo "Server container started"
REMOTE

  success "Server VM ready: http://$server_ip:$PORT_HTTP"
  echo "$server_ip"
}

create_client_vm() {
  local n="$1" server_ip="$2"
  local vm_name="${CLIENT_VMS[$((n-1))]}"

  info "Creating client VM $n: $vm_name (pointing to server $server_ip)..."

  gcloud compute instances create "$vm_name" \
    --project="$PROJECT_ID" \
    --zone="$ZONE" \
    --machine-type="$MACHINE_TYPE" \
    --image-family="$IMAGE_FAMILY" \
    --image-project="$IMAGE_PROJECT" \
    --boot-disk-size="$DISK_SIZE" \
    --tags="$NETWORK_TAG" \
    --scopes="cloud-platform" \
    --quiet 2>/dev/null || warn "VM $vm_name may already exist"

  wait_for_vm "$vm_name"

  # Generate CLIENT_TOKEN (JWT signed with JWT_SECRET) — use Python locally
  local client_id; client_id=$(python3 -c "import uuid; print(uuid.uuid4())" 2>/dev/null || uuidgen)
  local client_token; client_token=$(python3 -c "
import jwt, datetime, sys
payload = {'sub': '$client_id', 'type': 'client',
  'iat': datetime.datetime.now(datetime.UTC),
  'exp': datetime.datetime.now(datetime.UTC) + datetime.timedelta(days=720)}
print(jwt.encode(payload, '$JWT_SECRET', algorithm='HS256'))
" 2>/dev/null || echo "GENERATE_TOKEN_MANUALLY")

  gcloud compute ssh "$vm_name" --zone="$ZONE" --project="$PROJECT_ID" --quiet -- bash <<REMOTE
set -e

# Bootstrap Docker
$(_vm_bootstrap_docker)

# Download server CA cert (public — not the private key)
mkdir -p /app/certs
gcloud secrets versions access latest --secret=matcha-tls-cert --project=${PROJECT_ID} > /app/certs/server.crt

# Clone repo
git clone --branch ${GIT_BRANCH} ${GIT_REPO} /opt/matcha-cloud 2>/dev/null || \
  (cd /opt/matcha-cloud && git pull origin ${GIT_BRANCH})
cd /opt/matcha-cloud

# Build client image
docker build -f client/Dockerfile -t matcha-client:latest .

# Stop old container
docker rm -f matcha-client 2>/dev/null || true

# Run client
docker run -d \
  --name matcha-client \
  --restart=always \
  -p ${PORT_CLIENT}:8001 \
  -v /app/data:/app/data \
  -v /app/certs:/app/certs:ro \
  -e SERVER_URI=wss://${server_ip}:${PORT_WSS} \
  -e CLIENT_TOKEN=${client_token} \
  -e TLS_CA_CERT_PATH=/app/certs/server.crt \
  -e HTTP_PORT=8001 \
  matcha-client:latest

echo "Client container started"
REMOTE

  local client_ip; client_ip=$(get_external_ip "$vm_name")
  success "Client $n VM ready: http://$client_ip:$PORT_CLIENT"
}

show_summary() {
  local server_ip; server_ip=$(get_external_ip "$SERVER_VM")

  echo ""
  echo -e "${GREEN}═══════════════════════════════════════════════╗${NC}"
  echo -e "${GREEN}   matcha-cloud deployment summary              ${NC}"
  echo -e "${GREEN}═══════════════════════════════════════════════╝${NC}"
  echo ""
  echo -e "  ${CYAN}Dashboard (server):${NC}"
  echo -e "    http://${server_ip}:${PORT_HTTP}"
  echo -e "    wss://${server_ip}:${PORT_WSS}  (WebSocket)"
  echo ""
  echo -e "  ${CYAN}Default credentials:${NC}"
  echo -e "    Username : ${MATCHA_USER}"
  echo -e "    Password : ${MATCHA_PASSWORD}"
  echo ""
  echo -e "  ${CYAN}Client nodes:${NC}"
  for vm in "${CLIENT_VMS[@]}"; do
    local ip; ip=$(get_external_ip "$vm" 2>/dev/null || echo "pending")
    echo -e "    $vm  →  http://${ip}:${PORT_CLIENT}"
  done
  echo ""
  echo -e "  ${YELLOW}Note:${NC} Clients use self-signed TLS. Browser will warn — this is expected."
  echo -e "  ${YELLOW}Note:${NC} JWT_SECRET for this deployment: ${JWT_SECRET}"
  echo -e "         Save it! It's needed to issue new CLIENT_TOKENs."
  echo ""
}

# ══════════════════════════════════════════════════════════════════════════════
# DESTROY
# ══════════════════════════════════════════════════════════════════════════════

destroy() {
  warn "This will DELETE all matcha-cloud VMs and firewall rules in project ${PROJECT_ID}."
  read -r -p "Type 'yes' to confirm: " confirm
  [[ "$confirm" == "yes" ]] || { info "Aborted."; exit 0; }

  info "Deleting VMs..."
  for vm in "$SERVER_VM" "${CLIENT_VMS[@]}"; do
    gcloud compute instances delete "$vm" \
      --zone="$ZONE" --project="$PROJECT_ID" --quiet 2>/dev/null && \
      success "Deleted VM $vm" || warn "VM $vm not found"
  done

  info "Deleting firewall rules..."
  for rule in matcha-allow-http matcha-allow-wss matcha-allow-client; do
    gcloud compute firewall-rules delete "$rule" \
      --project="$PROJECT_ID" --quiet 2>/dev/null && \
      success "Deleted rule $rule" || warn "Rule $rule not found"
  done

  info "Deleting secrets..."
  for secret in matcha-tls-cert matcha-tls-key matcha-jwt-secret; do
    gcloud secrets delete "$secret" \
      --project="$PROJECT_ID" --quiet 2>/dev/null && \
      success "Deleted secret $secret" || warn "Secret $secret not found"
  done

  success "Teardown complete"
}

# ══════════════════════════════════════════════════════════════════════════════
# STATUS
# ══════════════════════════════════════════════════════════════════════════════

status_check() {
  info "Checking VM status..."
  for vm in "$SERVER_VM" "${CLIENT_VMS[@]}"; do
    local st; st=$(gcloud compute instances describe "$vm" \
      --zone="$ZONE" --project="$PROJECT_ID" \
      --format="get(status)" 2>/dev/null || echo "NOT_FOUND")
    local ip; ip=$(get_external_ip "$vm" 2>/dev/null || echo "N/A")
    echo -e "  ${CYAN}$vm${NC}  status=$st  ip=$ip"
  done
}

# ══════════════════════════════════════════════════════════════════════════════
# MAIN
# ══════════════════════════════════════════════════════════════════════════════

main() {
  case "${1:-deploy}" in
    destroy) check_prerequisites; destroy ;;
    status)  check_prerequisites; status_check ;;
    deploy|"")
      check_prerequisites
      enable_apis
      create_firewall_rules
      generate_and_upload_certs

      # Create server and capture its IP
      server_ip=$(create_server_vm)

      # Create 3 clients in sequence (could be parallelized)
      for i in 1 2 3; do
        create_client_vm "$i" "$server_ip"
      done

      show_summary
      ;;
    *)
      echo "Usage: $0 [deploy|destroy|status]"
      exit 1
      ;;
  esac
}

main "$@"
